<?php
return [
    'transaksi' => [
        'columns' => [
            'id' => 'id_trx',
            'invoice_no' => 'no_invoice',
            'total_weight' => 'total_berat',
            'shipping_fee' => 'ongkos_kirim',
            'total_price' => 'total_harga',
            'user_code' => 'kode_user',
            'user_id' => 'id_user',
            'shipping_address' => 'alamat_penerima',
            'shipping_date' => 'tgl_kirim',
            'expedition_id' => 'id_ekspedisi',
            'shipping_type' => 'jenis_pengiriman',
            'transaction_date' => 'tgl_trx'
        ],
        'regex' => [
            'id' => "/[^0-9]/",
            'invoice_no' => "/[^0-9A-Z]/",
            'total_weight' => "/[^0-9]/",
            'shipping_fee' => "/[^0-9]/",
            'total_price' => "/[^0-9]/",
            'user_code' => "/[^0-9]/",
            'user_id' => "/[^0-9]/",
            'shipping_address' => "",
            'shipping_date' => "date",
            'expedition_id' => "/[^0-9]/",
            'shipping_type' => "/[^a-zA-Z]/",
            'transaction_date' => "date",
        ],
        'mandatory' => [
            'id' => true,
            'invoice_no' => true,
            'total_weight' => true,
            'shipping_fee' => true,
            'total_price' => true,
            'user_code' => true,
            'user_id' => true,
            'shipping_address' => true,
            'shipping_date' => false,
            'expedition_id' => true,
            'shipping_type' => true,
            'transaction_date' => false,
        ],
        'limitter' => [
            'id' => 6,
            'invoice_no' => 2,
            'total_weight' => 6,
            'shipping_fee' => 4,
            'total_price' => 3,
            'user_code' => 1,
            'user_id' => 1,
            'shipping_address' => 2,
            'shipping_date' => 20,
            'expedition_id' => 20,
            'shipping_type' => 20,
            'transaction_date' => 20,
        ],
    ],
    'penjualan' => [
        'columns' => [
            'id' => 'id_trx',
            'invoice_no' => 'no_invoice',
            'total_weight' => 'total_berat',
            'shipping_fee' => 'ongkos_kirim',
            'total_price' => 'total_harga',
            'total_sale' => 'total_harga_beli',
            'user_code' => 'kode_user',
            'shipping_address' => 'alamat_penerima',
            'shipping_date' => 'tgl_kirim',
            'expedition_id' => 'id_ekspedisi',
            'shipping_type' => 'jenis_pengiriman',
            'sales_date' => 'tgl_trx'
        ],
        'regex' => [
            'id' => "/[^0-9]/",
            'invoice_no' => "/[^0-9A-Z]/",
            'total_weight' => "/[^0-9]/",
            'shipping_fee' => "/[^0-9]/",
            'total_price' => "/[^0-9]/",
            'total_sale' => "/[^0-9]/",
            'user_code' => "/[^0-9]/",
            'shipping_address' => "",
            'shipping_date' => "date",
            'expedition_id' => "/[^0-9]/",
            'shipping_type' => "/[^a-zA-Z]/",
            'sales_date' => "date",
        ],
        'mandatory' => [
            'id' => true,
            'invoice_no' => true,
            'total_weight' => true,
            'shipping_fee' => true,
            'total_price' => true,
            'total_sale' => true,
            'user_code' => true,
            'shipping_address' => true,
            'shipping_date' => false,
            'expedition_id' => true,
            'shipping_type' => true,
            'sales_date' => false,
        ],
        'limitter' => [
            'id' => 6,
            'invoice_no' => 2,
            'total_weight' => 6,
            'shipping_fee' => 4,
            'total_price' => 3,
            'total_sale' => 1,
            'user_code' => 1,
            'shipping_address' => 2,
            'shipping_date' => 20,
            'expedition_id' => 20,
            'shipping_type' => 20,
            'sales_date' => 20,
        ],
    ],
    'penjualan_detail' => [
        'columns' => [
            'id' => 'id_trx_detail',
            'sales_id' => 'id_trx',
            'invoice_no' => 'no_invoice',
            'product_id' => 'id_produk',
            'qty' => 'jml_barang',
            'weight' => 'berat',
            'unit_price' => 'harga_satuan',
            'discount' => 'diskon',
            'price' => 'harga',
        ],
        'regex' => [
            'id' => "/[^0-9]/",
            'sales_id' => "/[^0-9]/",
            'invoice_no' => "/[^0-9A-Z]/",
            'product_id' => "/[^0-9]/",
            'qty' => "/[^0-9]/",
            'weight' => "/[^0-9]/",
            'unit_price' => "/[^0-9]/",
            'discount' => "/[^0-9.]/",
            'price' => "/[^0-9]/",
        ],
        'mandatory' => [
            'id' => true,
            'sales_id' => true,
            'invoice_no' => true,
            'product_id' => true,
            'qty' => true,
            'weight' => true,
            'unit_price' => true,
            'discount' => true,
            'price' => true,
        ],
        'limitter' => [
            'id' => 6,
            'sales_id' => 2,
            'invoice_no' => 6,
            'product_id' => 4,
            'qty' => 3,
            'weight' => 1,
            'unit_price' => 1,
            'discount' => 2,
            'price' => 20,
        ],
    ],
    'barang' => [
        'columns' => [
            'id' => 'id_produk',
            'name' => 'nama',
            'category_id' => 'id_kategori',
            'weight' => 'berat',
            'price' => 'harga_beli',
            'stock' => 'stok',
            'sale' => 'harga_jual',
        ],
        'regex' => [
            'id' => "/[^0-9]/",
            'name' => "",
            'category_id' => "/[^0-9]/",
            'weight' => "/[^0-9]/",
            'price' => "/[^0-9]/",
            'stock' => "/[^0-9]/",
            'sale' => "/[^0-9]/",
        ],
        'mandatory' => [
            'id' => true,
            'name' => true,
            'category_id' => true,
            'weight' => true,
            'price' => true,
            'stock' => true,
            'sale' => true,
        ],
        'limitter' => [
            'id' => 6,
            'category_id' => 2,
            'name' => 6,
            'weight' => 4,
            'price' => 3,
            'stock' => 1,
            'sale' => 1,
        ],
    ],
    'ticket' => [
        'columns' => [
            'ticket_code' => 'ticket_code',
            'ticket_date' => 'ticket_date',
            'customer_id' => 'customer_id',
            'subject' => 'subject',
            'product_id' => 'id_product',
            'issue' => 'issue',
        ],
        'regex' => [
            'ticket_code' => "/[^0-9A-Z]/",
            'ticket_date' => "date",
            'customer_id' => "/[^0-9]/",
            'subject' => "",
            'product_id' => "/[^0-9A-Z]/",
            'issue' => "",
        ],
        'mandatory' => [
            'ticket_code' => true,
            'ticket_date' => false,
            'customer_id' => true,
            'subject' => true,
            'product_id' => true,
            'issue' => true,
        ],
        'limitter' => [
            'ticket_code' => 2,
            'ticket_date' => 6,
            'customer_id' => 4,
            'subject' => 3,
            'product_id' => 1,
            'issue' => 1,
        ],
    ],
    'ticket_process' => [
        'columns' => [
            'ticket_code' => 'ticket_code',
            'status' => 'status',
            'user_id' => 'user_id',
            'update_date' => 'update_date',
        ],
        'regex' => [
            'ticket_code' => "/[^0-9A-Z]/",
            'status' => "/[^A-Z]/",
            'user_id' => "/[^0-9A-Z]/",
            'update_date' => "date",
        ],
        'mandatory' => [
            'ticket_code' => true,
            'status' => false,
            'user_id' => true,
            'update_date' => false,
        ],
        'limitter' => [
            'ticket_code' => 2,
            'status' => 6,
            'user_id' => 4,
            'update_date' => 3,
        ],
    ],
];
